// ============================================================================
// Task 130：FSR1 RCAS（Robust Contrast Adaptive Sharpening）pass 2 着色器源。
//
// 参照 mpv 的 FSR.glsl（user_shaders）实现口径：
//   - uniform uSharpness ∈ [0,1]，越大越锐，默认 0.2（mpv 同默认）；
//   - 映射到 AMD FsrRcasCon 的 stops 语义（0.0=最大锐化，N>0=减少 N 档）：
//       stops = 2.0 * (1.0 - SHARPNESS)
//     即 SHARPNESS=1 -> 0 stops（最锐）、SHARPNESS=0 -> 2 stops（近无锐化），
//     与 mpv `FsrRcasCon(con, mix(0.0, 2.0, -SHARPNESS))` 的曲线一致。
//
// 与 EASU 源（FSRShaderSource.h，#version 450 全量 ffx 头）的差异——刻意精简：
//   - 只保留 32-bit non-packed 路径需要的宏与 FsrRcasCon/FsrRcasF 两个函数
//     （AMD FSR1 1.20210629 逐字移植，fsr_easu_fsr1.h 对应段）；
//   - FsrRcasCon 的 con[1]（packed half，仅 16-bit 路径消费）置 0 并注释——
//     避开 packHalf2x16 的 GLSL 4.20 / Task84 zink 4.10 cap 依赖；32-bit
//     FsrRcasF 只读 con.x，行为逐位一致；
//   - 采样回调用 texelFetch（1:1 锐化，不经过 MIN/MAG filter）——ESSL 300
//     兼容（Task80 教训：gather 在转译目标上不存在）。
//
// alpha 透传（Amethyst 特有，mpv 不需要）：osm_bridge 的 Task103/104 哨兵把
//   per-frame marker 写进 EASU 输出的 alpha 通道；RCAS 直写 alpha=1.0 会把
//   哨兵抹掉、验证链断裂。这里从中心像素原样透传 alpha，RGB 走锐化。
//
// 链接纪律（bd71210 教训）：本源用 static const（internal linkage）——
//   osm_bridge.mm / mgl_fsr.mm / MobileGlues FSR1.cpp 三个 TU 各持一份私有
//   副本，不存在跨 TU 强符号冲突（FSRShaderSource.h 的非 static 全局定义
//   曾在两个 C++ TU 间撞车）。
// ============================================================================

static const char *const FSR_RCAS_FSSource = R"fsr_rcas(#version 450

#define A_GPU 1
#define A_GLSL 1
#define FSR_RCAS_F 1

// ---- ffx_a.h GLSL 32-bit 精简（逐字对应 FSRShaderSource.h 的 GLSL 段）----
#define A_STATIC
#define AF1 float
#define AF2 vec2
#define AF3 vec3
#define AF4 vec4
#define AU1 uint
#define AU2 uvec2
#define AU4 uvec4
#define ASU1 int
#define ASU2 ivec2
#define outAU4 out AU4
#define varAF2(x) AF2 x
#define initAF2(x,y) AF2(x,y)
AF1 AF1_x(AF1 a){return AF1(a);}
AF4 AF4_x(AF1 a){return AF4(a,a,a,a);}
#define AF1_(a) AF1_x(AF1(a))
#define AF4_(a) AF4_x(AF1(a))
AU1 AU1_x(AU1 a){return AU1(a);}
#define AU1_(a) AU1_x(AU1(a))
#define AU1_AF1(x) floatBitsToUint(AF1(x))
#define AF1_AU1(x) uintBitsToFloat(AU1(x))
A_STATIC AF1 AExp2F1(AF1 a){return exp2(a);}
A_STATIC AF1 ASatF1(AF1 a){return min(1.0,max(0.0,a));}
A_STATIC AF1 AMax3F1(AF1 x,AF1 y,AF1 z){return max(x,max(y,z));}
A_STATIC AF1 AMin3F1(AF1 x,AF1 y,AF1 z){return min(x,min(y,z));}
A_STATIC AF1 ARcpF1(AF1 a){return 1.0/a;}
A_STATIC AF1 APrxMedRcpF1(AF1 a){AF1 b=AF1_AU1(AU1_(0x7ef19fff)-AU1_AF1(a));return b*(-b*a+AF1_(2.0));}

// ---- ffx_fsr1.h RCAS 常数设置（AMD 逐字，con[1] 见头注释）----
#define FSR_RCAS_LIMIT (0.25-(1.0/16.0))
A_STATIC void FsrRcasCon(
outAU4 con,
// The scale is {0.0 := maximum, to N>0, where N is the number of stops (halving) of the reduction of sharpness}.
AF1 sharpness){
 // Transform from stops to linear value.
 sharpness=AExp2F1(-sharpness);
 varAF2(hSharp)=initAF2(sharpness,sharpness);
 con[0]=AU1_AF1(sharpness);
 // 32-bit non-packed path consumes con.x only; the packed-half con[1] is a
 // 16-bit-path constant -- zeroed here to avoid packHalf2x16 (GLSL 4.20 /
 // ESSL 3.20 gate, Task84 zink 4.10 lesson). Bit-identical for this path.
 con[1]=AU1_(0);
 con[2]=0;
 con[3]=0;}

// ---- ffx_fsr1.h RCAS 滤波（AMD 32-bit non-packed 逐字）----
#if defined(A_GPU)&&defined(FSR_RCAS_F)
 // Input callback prototypes that need to be implemented by calling shader
 AF4 FsrRcasLoadF(ASU2 p);
 void FsrRcasInputF(inout AF1 r,inout AF1 g,inout AF1 b);
//------------------------------------------------------------------------------------------------------------------------------
 void FsrRcasF(
 out AF1 pixR, // Output values, non-vector so port between RcasFilter() and RcasFilterH() is easy.
 out AF1 pixG,
 out AF1 pixB,
 AU2 ip, // Integer pixel position in output.
 AU4 con){ // Constant generated by RcasSetup().
  // Algorithm uses minimal 3x3 pixel neighborhood.
  //    b
  //  d e f
  //    h
  ASU2 sp=ASU2(ip);
  AF3 b=FsrRcasLoadF(sp+ASU2( 0,-1)).rgb;
  AF3 d=FsrRcasLoadF(sp+ASU2(-1, 0)).rgb;
  AF3 e=FsrRcasLoadF(sp).rgb;
  AF3 f=FsrRcasLoadF(sp+ASU2( 1, 0)).rgb;
  AF3 h=FsrRcasLoadF(sp+ASU2( 0, 1)).rgb;
  // Rename (32-bit) or regroup (16-bit).
  AF1 bR=b.r;
  AF1 bG=b.g;
  AF1 bB=b.b;
  AF1 dR=d.r;
  AF1 dG=d.g;
  AF1 dB=d.b;
  AF1 eR=e.r;
  AF1 eG=e.g;
  AF1 eB=e.b;
  AF1 fR=f.r;
  AF1 fG=f.g;
  AF1 fB=f.b;
  AF1 hR=h.r;
  AF1 hG=h.g;
  AF1 hB=h.b;
  // Run optional input transform.
  FsrRcasInputF(bR,bG,bB);
  FsrRcasInputF(dR,dG,dB);
  FsrRcasInputF(eR,eG,eB);
  FsrRcasInputF(fR,fG,fB);
  FsrRcasInputF(hR,hG,hB);
  // Luma times 2.
  AF1 bL=bB*AF1_(0.5)+(bR*AF1_(0.5)+bG);
  AF1 dL=dB*AF1_(0.5)+(dR*AF1_(0.5)+dG);
  AF1 eL=eB*AF1_(0.5)+(eR*AF1_(0.5)+eG);
  AF1 fL=fB*AF1_(0.5)+(fR*AF1_(0.5)+fG);
  AF1 hL=hB*AF1_(0.5)+(hR*AF1_(0.5)+hG);
  // Noise detection.
  AF1 nz=AF1_(0.25)*bL+AF1_(0.25)*dL+AF1_(0.25)*fL+AF1_(0.25)*hL-eL;
  nz=ASatF1(abs(nz)*APrxMedRcpF1(AMax3F1(AMax3F1(bL,dL,eL),fL,hL)-AMin3F1(AMin3F1(bL,dL,eL),fL,hL)));
  nz=AF1_(-0.5)*nz+AF1_(1.0);
  // Min and max of ring.
  AF1 mn4R=min(AMin3F1(bR,dR,fR),hR);
  AF1 mn4G=min(AMin3F1(bG,dG,fG),hG);
  AF1 mn4B=min(AMin3F1(bB,dB,fB),hB);
  AF1 mx4R=max(AMax3F1(bR,dR,fR),hR);
  AF1 mx4G=max(AMax3F1(bG,dG,fG),hG);
  AF1 mx4B=max(AMax3F1(bB,dB,fB),hB);
  // Immediate constants for peak range.
  AF2 peakC=AF2(1.0,-1.0*4.0);
  // Limiters, these need to be high precision RCPs.
  AF1 hitMinR=min(mn4R,eR)*ARcpF1(AF1_(4.0)*mx4R);
  AF1 hitMinG=min(mn4G,eG)*ARcpF1(AF1_(4.0)*mx4G);
  AF1 hitMinB=min(mn4B,eB)*ARcpF1(AF1_(4.0)*mx4B);
  AF1 hitMaxR=(peakC.x-max(mx4R,eR))*ARcpF1(AF1_(4.0)*mn4R+peakC.y);
  AF1 hitMaxG=(peakC.x-max(mx4G,eG))*ARcpF1(AF1_(4.0)*mn4G+peakC.y);
  AF1 hitMaxB=(peakC.x-max(mx4B,eB))*ARcpF1(AF1_(4.0)*mn4B+peakC.y);
  AF1 lobeR=max(-hitMinR,hitMaxR);
  AF1 lobeG=max(-hitMinG,hitMaxG);
  AF1 lobeB=max(-hitMinB,hitMaxB);
  AF1 lobe=max(AF1_(-FSR_RCAS_LIMIT),min(AMax3F1(lobeR,lobeG,lobeB),AF1_(0.0)))*AF1_AU1(con.x);
  // Apply noise removal.
  #ifdef FSR_RCAS_DENOISE
   lobe*=nz;
  #endif
  // Resolve, which needs the medium precision rcp approximation to avoid visible tonality changes.
  AF1 rcpL=APrxMedRcpF1(AF1_(4.0)*lobe+AF1_(1.0));
  pixR=(lobe*bR+lobe*dR+lobe*hR+lobe*fR+eR)*rcpL;
  pixG=(lobe*bG+lobe*dG+lobe*hG+lobe*fG+eG)*rcpL;
  pixB=(lobe*bB+lobe*dB+lobe*hB+lobe*fB+eB)*rcpL;
  return;}
#endif

// ---- 入口（uniform 布局与 EASU 源同构；VS 复用 FSR_VSSource）----
uniform sampler2D uInputTex;
uniform float uSharpness;   // mpv 口径：[0,1]，越大越锐，默认 0.2
in vec2 vTexCoord;
out vec4 oFragColor;

// ---- 边界 clamp（Task164，Amethyst）----
// fullscreen-quad 入口在边缘像素必然产生 p+(0,-1)/(-1,0)/(1,0)/(0,1) 的
// 越界 tap：Mesa（zink）对越界 texelFetch 返回垃圾值但无害；ANGLE Metal
// 映射到 MTLTexture read:，越界读是未定义行为——M 系驱动实测可整帧废掉
// （fps/swap 全绿、屏幕全黑，即 ES/4.0 黑屏形态）。AMD 原版假设调用方
// 保证边界（mpv hook 天然 clamp），这里用 textureSize 在 shader 内自查，
// 零调用方侵入。textureSize 是 uniform-rate 查询，编译器 CSE 提升后
// 每像素开销可忽略。
AF4 FsrRcasLoadClamped(ASU2 p) {
    ASU2 ame164_max = ASU2(textureSize(uInputTex, 0)) - ASU2(1);
    p = clamp(p, ASU2(0), ame164_max);
    return texelFetch(uInputTex, p, 0);
}
AF4 FsrRcasLoadF(ASU2 p) { return FsrRcasLoadClamped(p); }
void FsrRcasInputF(inout AF1 r, inout AF1 g, inout AF1 b) {}

void main() {
    AU4 con;
    // mpv FSR.glsl 映射：SHARPNESS [0,1] -> AMD stops = 2*(1-SHARPNESS)。
    // 0.2（默认）-> 1.6 stops：轻-中档锐化；1.0 -> 0 stops：最大锐化。
    FsrRcasCon(con, AF1_(2.0) * (AF1_(1.0) - clamp(uSharpness, AF1_(0.0), AF1_(1.0))));
    AF3 c;
    FsrRcasF(c.x, c.y, c.z, AU2(gl_FragCoord.xy), con);
    // alpha 透传（Amethyst）：Task103/104 哨兵住在 EASU 输出的 alpha 通道，
    // RCAS 只算 RGB；alpha 从中心像素原样带回，哨兵链不断。
    AF4 center = FsrRcasLoadF(ASU2(gl_FragCoord.xy));
    oFragColor = vec4(c, center.a);
}
)fsr_rcas";
